package week3.day2;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;

public class selenium {
	public static void main(String[] args) {
		ChromeDriver driver = new ChromeDriver();
		//EdgeDriver driver = new EdgeDriver();
		driver.get("http://leaftaps.com/opentaps/control/main");
		driver.manage().window().maximize();
		WebElement userName=driver.findElement(By.id("username"));
		userName.sendKeys("DemoCsr");
		WebElement password =driver.findElement(By.id("password"));
		password.sendKeys("crmsfa");
		driver.findElement(By.className("decorativeSubmit")).click();
		driver.findElement(By.linkText("CRM/SFA")).click();
		WebElement clickCreateLead=driver.findElement(By.linkText("Leads"));
		clickCreateLead.click();
		WebElement clickLead=driver.findElement(By.partialLinkText("Create"));
		clickLead.click();
		WebElement companyName=driver.findElement(By.id("createLeadForm_companyName")); 
		companyName.sendKeys("testleaf");
		WebElement firstName=driver.findElement(By.id("createLeadForm_firstName"));
		firstName.sendKeys("priyadharshan");
		WebElement lastName=driver.findElement(By.id("createLeadForm_lastName"));
		lastName.sendKeys("G");
		WebElement fristNameLocal=driver.findElement(By.id("createLeadForm_firstNameLocal"));
		fristNameLocal.sendKeys("dharshan");
		WebElement lastNameLocal=driver.findElement(By.id("createLeadForm_lastNameLocal"));
		lastNameLocal.sendKeys("G");
		WebElement salutation=driver.findElement(By.id("createLeadForm_personalTitle"));
		salutation.sendKeys("Mr");
		WebElement title=driver.findElement(By.id("createLeadForm_generalProfTitle"));
		title.sendKeys("My Project");
		WebElement deparment=driver.findElement(By.id("createLeadForm_departmentName"));
		deparment.sendKeys("software test");
		WebElement code=driver.findElement(By.id("createLeadForm_departmentName"));
		code.sendKeys("1006");
		WebElement employeeName=driver.findElement(By.id("createLeadForm_numberEmployees"));
		employeeName.sendKeys("priyadharshan");
		WebElement description=driver.findElement(By.id("createLeadForm_description"));
		description.sendKeys("software testing");
		WebElement ticketSymbol=driver.findElement(By.id("createLeadForm_tickerSymbol"));
		ticketSymbol.sendKeys("t");
		WebElement importandNote=driver.findElement(By.id("createLeadForm_importantNote"));
		importandNote.sendKeys("this is very importand");
		WebElement countryCode=driver.findElement(By.id("createLeadForm_primaryPhoneCountryCode"));
		countryCode.sendKeys("22");
		WebElement areaCode=driver.findElement(By.id("createLeadForm_primaryPhoneAreaCode"));
		areaCode.sendKeys("600537");
		WebElement extension=driver.findElement(By.id("createLeadForm_primaryPhoneExtension"));
		extension.sendKeys("extension");
		WebElement emailAddress=driver.findElement(By.id("createLeadForm_primaryEmail"));
		emailAddress.sendKeys("priyadharshan000@gmail.com");
		WebElement phoneNumber=driver.findElement(By.id("createLeadForm_primaryPhoneNumber"));
		phoneNumber.sendKeys("8045223513");
		WebElement personAskFor=driver.findElement(By.id("createLeadForm_primaryPhoneAskForName"));
		personAskFor.sendKeys("manager");
		WebElement webUrl=driver.findElement(By.id("createLeadForm_primaryWebUrl"));
		webUrl.sendKeys("https://www.testleaf.com/");
		WebElement address1=driver.findElement(By.className("generalAddress1"));
		address1.sendKeys("10/83 jj nagar chennai");
		WebElement city=driver.findElement(By.id("createLeadForm_generalCity"));
		city.sendKeys("chennai");
		WebElement ZipPostalCode=driver.findElement(By.id("createLeadForm_generalPostalCode"));
		ZipPostalCode.sendKeys("44");
		WebElement zipPostCodeExtension=driver.findElement(By.id("createLeadForm_generalPostalCodeExt"));
		zipPostCodeExtension.sendKeys("600044");
		WebElement attensionName=driver.findElement(By.id("createLeadForm_generalAttnName"));
		attensionName.sendKeys("priya");
		WebElement address2=driver.findElement(By.id("createLeadForm_generalAddress2"));
		address2.sendKeys("12/234 jjnagar chennai");
		WebElement clickCreateLeadButtom=driver.findElement(By.name("submitButton"));
		clickCreateLeadButtom.click();	
		                                                    }
}